sudo: false
dist: trusty

language: python

python:
  - 3.5
  - 2.7

addons:
  apt:
    packages:
    - libsaxonb-java
    - inkscape
    - default-jre
    - texlive-base
    - texlive-xetex
    - texlive-latex-recommended
    - texlive-latex-extra
    - texlive-extra-utils
    - texlive-fonts-recommended
    - texlive-font-utils
    - texlive-lang-french
    - texlive-math-extra
    - texlive-pictures
    - latex-xcolor
    - texlive-bibtex-extra


install:
    - wget http://files.basex.org/releases/8.6.1/BaseX861.zip && unzip BaseX861.zip && rm BaseX861.zip
    - pip install -r requirements.txt
    - export PATH=$PWD/basex/bin:$PATH

script:  make circonscriptions && cp circos.json output/ && cp circonscriptions/document.pdf output/ && tar czvf output.tar.gz output

cache:
  apt: true
  pip: true
  directories:
    - $PWD/raw
    - $PWD/data

deploy:
    provider: releases
    api_key: "$GH_TOKEN"
    file: "output.tar.gz"
    skip_cleanup: true
    on:
      tags: true

notifications:
  email:
    recipients:
      - lucas.gautheron@gmail.com
    on_success: change # default: change
on_failure: always
